name: fastrent
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.1.1
  get: 4.6.5
  flutter:
    sdk: flutter
  http: ^0.13.5
  shared_preferences: ^2.1.0
  go_router: ^7.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: lib/assets/fonts/Poppins-Medium.ttf
        - asset: lib/assets/fonts/Poppins-Light.ttf
        - asset: lib/assets/fonts/Poppins-Regular.ttf
